uv run main.py \
    --output_path logs \
    --dataset celeba \
    --dataset_path datasets/celeba-dataset \
    --experiment DFR \
    --sample_size 128 \
    --batch_size 512 \
    --learning_rate 0.001 \
    --pretrained_path checkpoints/dfr-ckpts/celeba/erm_seed1/final_checkpoint.pt \
    --l1 0.00 \
    --epochs 100 \
    --optimizer adam \
    --step_size 30 \
    --seed 0